"""add_last_reset_at

Revision ID: 6a81ce51de0f
Revises: 716dece24f3f
Create Date: 2026-05-10 11:05:36.413545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a81ce51de0f'
down_revision: Union[str, Sequence[str], None] = '716dece24f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_agents', sa.Column('last_reset_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_agents', 'last_reset_at')
    # ### end Alembic commands ###
